<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\PrjRefDddSolid.Communication\PrjRefDddSolid.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\PrjRefDddSolid.Exception\PrjRefDddSolid.Exception.csproj" />
    <ProjectReference Include="..\PrjRefDddSolid.Domain\PrjRefDddSolid.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
  </ItemGroup>

</Project>
